INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_DEMO_ASSYMETRIC_INPUT demo_assymetric_input)

FIND_PATH(
    DEMO_ASSYMETRIC_INPUT_INCLUDE_DIRS
    NAMES demo_assymetric_input/api.h
    HINTS $ENV{DEMO_ASSYMETRIC_INPUT_DIR}/include
        ${PC_DEMO_ASSYMETRIC_INPUT_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    DEMO_ASSYMETRIC_INPUT_LIBRARIES
    NAMES gnuradio-demo_assymetric_input
    HINTS $ENV{DEMO_ASSYMETRIC_INPUT_DIR}/lib
        ${PC_DEMO_ASSYMETRIC_INPUT_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DEMO_ASSYMETRIC_INPUT DEFAULT_MSG DEMO_ASSYMETRIC_INPUT_LIBRARIES DEMO_ASSYMETRIC_INPUT_INCLUDE_DIRS)
MARK_AS_ADVANCED(DEMO_ASSYMETRIC_INPUT_LIBRARIES DEMO_ASSYMETRIC_INPUT_INCLUDE_DIRS)

